/**
 * THE SECOND WITNESS — a pure comparison, plus the one entry point that reads
 * the file it writes.
 *
 * Run: npx tsx scripts/crosscheck.ts        (after data:theater and data:parse)
 *
 * ── WHAT THIS MEASURES ──────────────────────────────────────────────────────
 * Replay Theater indexes 258 Avatar Legends matches over 95 videos (2026-09-18).
 * 158 of the 244 rows at the contract sweep were segments inside VODs whose
 * uploaders are TRACKED CHANNELS here, so parse's known-anywhere ignore drops
 * them from ingestion entirely (checklist 12c). Out of ingestion scope is not out
 * of scope as EVIDENCE: each of those rows is a second human reading of the same
 * match — somebody typed two handles, a fighter and a support into a form, and
 * our parser read them out of the uploader's title.
 *
 * It produces no field and overwrites nothing. A disagreement goes to
 * data/theater-disagreements.json with both claims side by side; it never edits a
 * record, never outranks a confident parse, never outranks a human override. The
 * catalogue is a witness, not an authority.
 *
 * NOT data/review-queue.json, deliberately. In this repo that queue means
 * WITHHELD — pending items never reach videos.json (types/index.ts:1026-1043) —
 * and a contested row is a record we have already published and are not proposing
 * to unpublish on a third party's say-so. The queue is also REGENERATED by every
 * parse, so anything written there by another script is gone on the next run.
 *
 * ── CHECKLIST 12i'S SECOND SENTENCE IS THE HARD PART HERE ───────────────────
 * "Measure the independence before banking the number." The siblings answer it
 * with one figure: the share of overlapping rows whose catalogue upload_date
 * equals the VOD's publish date (97.27% on Strive, 98.7% on CotW), i.e. "the
 * submitter probably read the same title we did". That number exists on this game
 * too — 86.58% equal, 97.84% within ±1 day — and on its own it is the WRONG
 * question, because this catalogue is mostly SEGMENTS, and a segment's submitter
 * was not reading the video title at all. They were reading a chapter marker, or
 * the footage.
 *
 * So the reach is split THREE ways, over every row the pull joined:
 *
 *   chapter-transcribed  a chapter of the VOD already names both handles.
 *                        NEAR-DEPENDENT: the submitter could have copied it, and
 *                        so could a chapter-reading parser. 66 rows at the
 *                        2026-09-16 sweep, 69 of 258 at the 2026-09-18 one.
 *   title-transcribed    no naming chapter, but the VOD's own title names both
 *                        handles. NEAR-DEPENDENT for the same reason, and this is
 *                        the population our own parser reads. 57 rows, then 62.
 *   independent          neither text names both. Somebody watched the footage
 *                        and typed what they saw. 91 rows — 83 segments with no
 *                        naming chapter plus 8 whole uploads whose titles are
 *                        clickbait — then 88. THIS is the number worth banking.
 *
 * A fourth bucket, `partial`, holds rows where exactly one handle appears in the
 * text; it is neither, and folding it into either would flatter one of them.
 * scripts/channels.ts:1483-1488 asks for exactly this split, in those words.
 *
 * `classifyNameSource` below carries the one measurement that changed the design:
 * anchoring the chapter test to the row's OFFSET, the way the reference's chapter
 * reader does, under-counts by 22 rows on this catalogue and every one of them
 * lands in `independent`.
 *
 * ── WHAT COMPARES AGAINST WHAT ──────────────────────────────────────────────
 * Scoring needs a 1:1 claim, so only a video the catalogue lists ONCE, which we
 * hold as a whole-video record FROM A TRACKED CHANNEL, is compared. Both halves
 * matter and the second one is this game's:
 *   · the intake admits untagged rows (channels.ts `admitUntagged`), so 77 of the
 *     catalogue's videos can become records under a BARE video id. Excluding by
 *     the `@` in the id alone would compare every one of those against the row it
 *     was BUILT FROM and report a spotless 100% — the catalogue witnessing itself.
 *     `intake` is the dedupe key and names where a record came from; test that.
 *   · a video the catalogue cuts into segments has no single claim to compare, and
 *     those rows are the intake's own territory.
 *
 * ── THREE FIELDS, NOT TWO ───────────────────────────────────────────────────
 * Players, FIGHTERS and SUPPORTS, because the namespaces are separate here
 * (checklist 13) and folding them would destroy the only comparison that is
 * actually informative. The support column is filled on 100% of catalogue rows
 * and 27 of the 32 title channels never state a support at all, so `supports` is
 * mostly a measurement of what we do NOT know — which is the honest reading, and
 * the reason `weSilent` is its own bucket rather than a miss.
 *
 * The catalogue's own partition invariant is checked while we are here: every
 * support belongs to exactly one fighter (measured across all 462 sides of the
 * 2026-09-16 sweep), so a row whose support is not owned by its own fighter is a
 * row to look at. 0 today.
 *
 * ── EXACT ALIAS, NEVER FUZZY — AND EXACT MEANS THE WHOLE STRING ─────────────
 * The catalogue writes `Ming-Hua`, `Master Pakku`, `Ran and Shaw`, `P'Li`,
 * `Firelord Sozin`, `The Boulder` where a short-form table would write the last
 * word; data/supports.json takes the catalogue's spelling as canonical for
 * exactly this reason (types/index.ts:986-997). A string resolves only when the
 * roster matcher finds EXACTLY ONE span and that span covers the ENTIRE
 * normalised string — `matcher.one()` alone is a scan that would read "Sol Badguy
 * Player" as a character, and a witness that guesses is not a witness. Going
 * through buildAliasMatcher rather than a second table means the witness and the
 * parser share one vocabulary and one normalisation.
 *
 * ── WHY THIS FILE WRITES TO data/ AT ALL ────────────────────────────────────
 * checklist 12e puts every data/ write in parse, and on the siblings this
 * module is a pure function that scripts/parse-finish.ts calls, writes for and
 * renders from. Here parse-finish (the wave-2 parse track) does not import it, so
 * a pure function would have no caller — which is 12i's named failure in its
 * other direction: a witness with a reader that nothing runs. The entry point
 * below is therefore a STAGE of its own, with one write, running after parse and
 * reading what parse committed. It cannot leave the record pipeline half-written
 * because it never touches it. The tidy end state is parse-finish importing
 * `crossCheck` and owning the write; until then this is the reader 12i requires.
 *
 * AND IT READS WHAT IT WRITES. The artifact is the committed reading, and
 * report.md must render from what is COMMITTED rather than from this run's
 * memory: the witness is rebuilt from scratch on each pull and holds only the
 * pages that pull read, so a cursor morning's window is a different WINDOW, not a
 * different corpus, and rendering it would change a committed file every single
 * morning whether or not any RECORD had. So a FULL sweep measures and writes; the
 * block is then rendered from the file RE-READ FROM DISK, and the re-read numbers
 * are checked field by field against the reading that produced them — not
 * byte-compared, which for JSON is close enough to a tautology to pass on a Map
 * (measured: it does).
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { stripTheaterSponsor } from './channels';
import { VIDEO_ID } from './fetch-theater';
import { isPlaceholderHandle } from './parse';
import {
  aliasKey,
  buildAliasMatcher,
  buildSupportIndex,
  loadCharacters,
  loadSupports,
  normalizeText,
  playerId,
} from './roster';
import type { Chapter } from './fetch-theater';
import type { AliasMatcher, Namespace, SupportIndex } from './roster';
import type { MatchVideo } from '../types/index';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const RAW = join(ROOT, 'raw');
const DATA = join(ROOT, 'data');
const WITNESS = join(RAW, 'replayTheater.witness.json');
const ARTIFACT = join(DATA, 'theater-disagreements.json');

/** One catalogue entry, exactly as the catalogue publishes it. Everything is
 *  nullable: this is someone else's schema and we do not get to assume. */
export interface WitnessEntry {
  id?: number;
  game?: string | null;
  video_link?: string | null;
  tag?: string | null;
  upload_date?: string | null;
  p1_name?: string | null;
  p2_name?: string | null;
  p1_char?: string | null;
  p1_char2?: string | null;
  p1_char3?: string | null;
  p1_char4?: string | null;
  p2_char?: string | null;
  p2_char2?: string | null;
  p2_char3?: string | null;
  p2_char4?: string | null;
}

/** The VOD metadata the independence split needs, written by the pull beside the
 *  entries. NO SIBLING'S WITNESS CARRIES THIS, because no sibling had to answer
 *  "which of these rows was transcribed and which was watched". The chapters are
 *  derived ONCE, by scripts/fetch-theater.ts `chaptersOf`, so the pull's trust
 *  measurement and this split cannot disagree about what a chapter is. */
export interface WitnessVideo {
  title: string;
  uploader: string;
  publishedAt: string;
  durationSec: number;
  chapters: Chapter[];
}

/** raw/replayTheater.witness.json — written by scripts/fetch-theater.ts beside
 *  the intake dump. EVERY entry of the read window that passed the per-entry game
 *  gate, tagged and untagged, NOT cursor-gated. Nothing that reads it may build a
 *  record from it. */
export interface WitnessFile {
  mode?: 'cursor' | 'full';
  maxEntryId?: number;
  pagesRead?: number;
  hitBound?: boolean;
  entries?: WitnessEntry[];
  videos?: Record<string, WitnessVideo>;
}

/** One row the cross-check could not settle, carrying BOTH claims. This is what
 *  reaches data/theater-disagreements.json — never a rewritten record. */
export interface Disagreement {
  videoId: string;
  field: 'players' | 'characters' | 'supports';
  /** 0 or 1, in our record's side order. Absent for a whole-record player miss. */
  side?: number;
  ours: string[];
  theirs: string[];
  title: string;
}

/** A roster id the catalogue has no word for, and the id it writes instead.
 *  DERIVED per run, never declared — the day a fighter is renamed upstream the
 *  derivation reads the change instead of needing an edit. Nothing derives today:
 *  the catalogue writes all 12 released fighters and every one resolves. */
export interface BlindSpot {
  id: string;
  mergedInto: string;
  merged: number;
  sides: number;
}

/** Where a row's names could have come from. See the header. */
export type NameSource = 'chapter' | 'title' | 'partial' | 'independent' | 'unjoined';

export interface Independence {
  /** Rows classified (i.e. joined to a VOD this pull resolved). */
  rows: number;
  chapterTranscribed: number;
  titleTranscribed: number;
  partial: number;
  independent: number;
  /** Rows whose video this pull did not join — a cursor window holds entries whose
   *  VODs were resolved by an earlier run. Excluded from every share above rather
   *  than counted as independent, which is the direction that would flatter the
   *  number. */
  unjoined: number;
  /** The siblings' one-number version, kept so the two readings sit beside each
   *  other: rows whose catalogue upload_date equals the VOD's publish date. */
  sameDay: number;
}

export interface CrossCheckResult {
  compared: number;
  unmatched: number;
  segmented: number;
  players: {
    both: number;
    one: number;
    neither: number;
    flipped: number;
    placeholder: number;
    handleAffix: { ours: number; theirs: number; unrelated: number };
  };
  characters: {
    sides: number;
    agree: number;
    disagree: number;
    cannotWitness: number;
    blindSpot: number;
    unreadable: number;
    overCap: number;
  };
  supports: {
    sides: number;
    agree: number;
    disagree: number;
    /** WE said nothing — the common case, and not a miss: 27 of the 32 title
     *  channels never state a support. */
    weSilent: number;
    /** THEIR string resolves to no support id. */
    unreadable: number;
    /** Their support is not owned by their own fighter — the catalogue's own
     *  partition invariant, checked on the source that measured it. */
    ownerMismatch: number;
  };
  independence: Independence;
  blindSpots: BlindSpot[];
  disagreements: Disagreement[];
}

/**
 * data/theater-disagreements.json — the committed home of everything the
 * cross-check knows, written ONLY by a full sweep. See the header for why it is
 * committed rather than recomputed into report.md every morning.
 */
export interface WitnessArtifact {
  measured?: {
    /** The catalogue's high-water entry id at that sweep — names the sweep
     *  without a timestamp, so re-rendering it cannot churn the file. */
    atEntryId: number;
    compared: number;
    unmatched: number;
    segmented: number;
    players: CrossCheckResult['players'];
    characters: CrossCheckResult['characters'];
    supports: CrossCheckResult['supports'];
    independence: Independence;
  };
  blindSpots: BlindSpot[];
  disagreements: Disagreement[];
}

/**
 * Exact resolution of one catalogue string through the roster's own matcher:
 * exactly ONE span, covering the WHOLE normalised string, IN THE NAMESPACE THE
 * COLUMN DECLARES.
 *
 * The namespace argument is this game's (checklist 13). `Katara` resolves in BOTH
 * — she is a launch fighter and also Avatar Aang's support — so a namespace-blind
 * resolver reading the support column would hand back a fighter id and the
 * comparison would contest a correct record. `overlap` is returned rather than
 * swallowed so the caller can say the span was ambiguous.
 *
 * THE TWIN OF scripts/parse-finish.ts:1164-1177, which carries a private copy of
 * this function for the intake build. Two copies of an exactness rule is one too
 * many; this one is exported so that copy can become an import.
 */
export function exactAlias(
  matcher: AliasMatcher,
  text: string,
  ns: Namespace,
): { id?: string; overlap: boolean } {
  const t = normalizeText(text);
  if (t === '') return { overlap: false };
  const spans = matcher.find(t);
  if (spans.length !== 1) return { overlap: false };
  const s = spans[0]!;
  if (s.start !== 0 || s.end !== t.length) return { overlap: false };
  const id = ns === 'fighter' ? s.fighter : s.support;
  return { ...(id ? { id } : {}), overlap: !!s.fighter && !!s.support };
}

/** How many sides an id must be OUR reading of before its absence from the
 *  catalogue counts as a vocabulary gap rather than a coincidence, and how
 *  concentrated the catalogue's alternative has to be. Both are deliberately
 *  blunt: the test only has to separate "said X 330 times out of 331" from "three
 *  scattered sides on a two-page cursor morning". On a corpus this small the
 *  minimum is doing most of the work, and that is the safe direction — a blind
 *  spot wrongly derived would HOLD OUT real disagreements. */
const BLIND_SPOT_MIN_SIDES = 10;
const BLIND_SPOT_CONCENTRATION = 0.9;

/**
 * THE CATALOGUE CAN NAME ONE FIGHTER PER SIDE.
 *
 * `p*_char` is the fighter column and `p*_char2` is the support; char3/char4 are
 * null on 258 of 258 rows. So the schema ceiling for FIGHTERS is 1, not the
 * reference's 4 (ggst crosscheck.ts:362 `sideCap = 4`, counting all four columns
 * as characters). Our `MatchSide.characters` is an ordered union with no limit and
 * the corpus contains counter-picks — "Ozai, Toph", "Zuko/Katara" on five titles
 * (types/index.ts:782-791) — and a side of ours naming two fighters is one the
 * catalogue STRUCTURALLY could not have agreed with. Scoring it as a disagreement
 * would contest a correct record on a schema difference.
 */
const FIGHTER_CAP = 1;

const setEq = (a: string[], b: string[]): boolean => {
  const A = new Set(a);
  const B = new Set(b);
  return A.size === B.size && [...A].every((x) => B.has(x));
};

const cell = (e: WitnessEntry, key: string): string => {
  const v = (e as unknown as Record<string, unknown>)[key];
  return typeof v === 'string' ? v.trim() : '';
};
/** ONE COLUMN, NOT A FOLD. See the header and checklist 13. */
const fighterCell = (e: WitnessEntry, side: 1 | 2): string => cell(e, `p${side}_char`);
const supportCell = (e: WitnessEntry, side: 1 | 2): string => cell(e, `p${side}_char2`);

/**
 * WHERE COULD THIS ROW'S NAMES HAVE COME FROM?
 *
 * The question is transcribability, not alignment: was the text already there for
 * the submitter to copy? So the test is whether ANY chapter of the video names
 * both handles, not whether the chapter AT THE ROW'S OFFSET does — and the
 * difference is 20 rows, all of them in one direction.
 *
 * THE OFFSET-ANCHORED RULE IS OFF BY ONE ON A WHOLE VOD, MEASURED. The reference's
 * chapter reader takes the last chapter whose start is <= the offset (ggst
 * fetch-theater.ts:1163-1168), which is right for measuring whether the catalogue's
 * offsets LAND on the markers and wrong for asking where the names came from,
 * because this catalogue submits some offsets EARLY. On zD1wAGwENcY (dekillsage,
 * 11,139s, 24 rows — "Mix Masters Tournament #1") the offsets sit 60-75s BEFORE
 * their own chapter on 19 of 24 rows, so "the chapter at or before the offset" is
 * the PREVIOUS MATCH's chapter every time: row @1615 reads "TestMyLuck vs
 * namredoops" while the row is Archit3ct vs Leonidas Daimon, whose chapter starts
 * at 1675. Stage 0 saw the same lead ("about 58-77s before the chapter on 18 of 24
 * rows") and used the NEAREST chapter, which is why its split reads 66.
 *
 * Measured on the 2026-09-18 sweep of 258 rows: at-or-before scores 47
 * chapter-transcribed, nearest-by-distance 67, any-chapter 69 — and the 22 rows
 * the strict rule loses do not vanish, they land in `independent`, which is the
 * one direction that FLATTERS the headline number (126 independent under the
 * strict rule against 88 under this one). A measure of how much of a witness is
 * independent must never be able to gain from its own imprecision.
 *
 * Any-chapter rather than nearest-chapter because it needs no distance bound: the
 * consecutive-offset gap on this catalogue runs 116s at its tightest, a
 * nearest-chapter window wide enough for the 75s lead is within a coin flip of
 * that, and "some chapter of this video names these two people" is the honest
 * statement of what a submitter could have copied anyway. The ALIGNMENT reading —
 * how close the offsets sit to the markers — stays where it belongs, in the
 * pull's own recon (scripts/fetch-theater.ts), where it is printed under both
 * rules so this VOD's systematic lead is visible rather than buried in a low
 * agreement rate.
 *
 * Containment is alphanumeric-folded on both sides (`aliasKey`), which is what
 * makes `GSN|Flankroast` in a chapter match `Flankroast` in the catalogue and
 * `UnsafeOnHit`/`UnsafeonHit` one name. Sponsor prefixes are stripped from the
 * catalogue's handles first, for the same reason the comparison below strips them.
 * It stays a CONTAINMENT test and not a fuzzy one: Shirai Ryu TV's chapters write
 * `Bar Bar`, `XCalibur` and `Dark Water` where the catalogue writes `bar_barXII`,
 * `xcaliburbladez` and `Darkwater72`, and those rows are correctly NOT
 * transcriptions — the submitter knew a fuller handle than the chapter states.
 *
 * A one-character handle would match almost any text, so a key shorter than two
 * characters is not allowed to count as named — `♱` slugs to the empty key and
 * would otherwise mark every row it appears on as transcribed.
 */
export function classifyNameSource(
  e: WitnessEntry,
  video: WitnessVideo | undefined,
  stripSponsor: (h: string) => string,
): NameSource {
  if (!video) return 'unjoined';
  const keys = [e.p1_name ?? '', e.p2_name ?? ''].map((n) => aliasKey(stripSponsor(n)));
  const usable = keys.filter((k) => k.length >= 2);
  const hits = (text: string): number => {
    const t = aliasKey(text);
    return usable.filter((k) => t.includes(k)).length;
  };
  const namesBoth = (text: string): boolean => usable.length === 2 && hits(text) === 2;

  if (video.chapters.some((c) => namesBoth(c.title))) return 'chapter';
  if (namesBoth(video.title)) return 'title';
  if (video.chapters.some((c) => hits(c.title) >= 1) || hits(video.title) >= 1) return 'partial';
  return 'independent';
}

interface Side {
  /** The player identity key, or [] when the catalogue named nobody we can key. */
  players: string[];
  /** The raw handle after sponsor stripping, for the placeholder test —
   *  playerId() would turn `Unknown Player` into a perfectly good-looking id. */
  handle: string;
  fighters: string[];
  support: string | null;
  /** The catalogue's verbatim support string, for the unreadable bucket. */
  supportRaw: string;
}
interface Pair {
  videoId: string;
  title: string;
  ours: Side[];
  theirs: Side[];
}

/**
 * @param witness      every entry the pull saw, tagged and untagged, plus the
 *                     VOD metadata it joined
 * @param committed    our published records (data/videos.json)
 * @param matcher      the roster's alias matcher — the PARSER's own vocabulary,
 *                     used exactly (see exactAlias)
 * @param supportIndex data/supports.json's owner partition, for the catalogue's
 *                     own invariant
 * @param resolveKey   the repo's player identity key (roster.ts playerId)
 * @param stripSponsor channels.ts stripTheaterSponsor, applied to BOTH sides.
 *                     Ours already went through it at parse time and the strip is
 *                     idempotent; applying it here too makes the measurement
 *                     independent of that discipline
 * @param carriedBlindSpots
 *                     blind spots this repo has already derived and committed. A
 *                     blind spot is a fact about the CATALOGUE'S VOCABULARY, not
 *                     about a run, so it outlives the pull that found it: a full
 *                     sweep is authoritative and may retire one, a cursor run can
 *                     only ADD.
 */
export function crossCheck(
  witness: WitnessFile,
  committed: MatchVideo[],
  matcher: AliasMatcher,
  supportIndex: SupportIndex,
  resolveKey: (h: string) => string,
  stripSponsor: (h: string) => string,
  carriedBlindSpots: BlindSpot[] = [],
): CrossCheckResult {
  // ONLY WHOLE-VIDEO RECORDS FROM A TRACKED CHANNEL ARE COMPARABLE. See the
  // header: testing the `@` alone would let the catalogue witness itself on the
  // 77 single-row videos the intake publishes under a bare video id.
  const ours = new Map<string, MatchVideo>();
  for (const v of committed) {
    if (v.intake === 'replayTheater') continue;
    if (v.id.includes('@')) continue;
    ours.set(v.id, v);
  }

  const entries = witness.entries ?? [];
  const videos = witness.videos ?? {};
  // Grouped by video through the INTAKE's own id extractor, not a second copy of
  // it: a witness that reads links differently from the fetcher is comparing a
  // different set of rows than the one that was ingested.
  const byVideo = new Map<string, WitnessEntry[]>();
  for (const e of entries) {
    const m = VIDEO_ID.exec(e.video_link ?? '');
    if (!m) continue;
    byVideo.set(m[1]!, [...(byVideo.get(m[1]!) ?? []), e]);
  }

  const r: CrossCheckResult = {
    compared: 0,
    unmatched: 0,
    segmented: 0,
    players: {
      both: 0,
      one: 0,
      neither: 0,
      flipped: 0,
      placeholder: 0,
      handleAffix: { ours: 0, theirs: 0, unrelated: 0 },
    },
    characters: {
      sides: 0,
      agree: 0,
      disagree: 0,
      cannotWitness: 0,
      blindSpot: 0,
      unreadable: 0,
      overCap: 0,
    },
    supports: {
      sides: 0,
      agree: 0,
      disagree: 0,
      weSilent: 0,
      unreadable: 0,
      ownerMismatch: 0,
    },
    independence: {
      rows: 0,
      chapterTranscribed: 0,
      titleTranscribed: 0,
      partial: 0,
      independent: 0,
      unjoined: 0,
      sameDay: 0,
    },
    blindSpots: [],
    disagreements: [],
  };

  // ── the independence split, over EVERY row the pull saw ──────────────────
  // Not over the compared subset: this describes the SOURCE, not our overlap
  // with it, and the rows we do not hold are exactly the ones the intake's own
  // contribution comes from.
  for (const e of entries) {
    const m = VIDEO_ID.exec(e.video_link ?? '');
    const video = m ? videos[m[1]!] : undefined;
    const source = classifyNameSource(e, video, stripSponsor);
    if (source === 'unjoined') {
      r.independence.unjoined++;
      continue;
    }
    r.independence.rows++;
    if (source === 'chapter') r.independence.chapterTranscribed++;
    else if (source === 'title') r.independence.titleTranscribed++;
    else if (source === 'partial') r.independence.partial++;
    else r.independence.independent++;
    if (video && (e.upload_date ?? '') === video.publishedAt.slice(0, 10)) {
      r.independence.sameDay++;
    }
  }

  // ── pass 1: align, and nothing else ─────────────────────────────────────
  // ORIENTATION FIRST. The catalogue's p1/p2 is the submitter's reading of the
  // screen and ours is the title's; they agree on essentially every row but not by
  // contract, and comparing characters across a swapped pair would manufacture two
  // disagreements out of none. Measured on this game the risk is live rather than
  // theoretical: teo1029's index witness (row 484973) is the reverse of that
  // channel's own title order (types/index.ts:500-505). Aligned on the HANDLES,
  // which is the field the two sources agree on most.
  //
  // NO NAME SPLITTING. There is no playerSep on this game (channels.ts): '/' inside
  // a bracket means FIGHTER/SUPPORT on twelve channels, and the catalogue carries
  // the handle "Vik/Jagi" on five sides, which is one person.
  const pairs: Pair[] = [];
  for (const [videoId, list] of byVideo) {
    const mine = ours.get(videoId);
    if (!mine) {
      r.unmatched++;
      continue;
    }
    if (list.length > 1) {
      r.segmented++;
      continue;
    }
    const e = list[0]!;
    r.compared++;

    const theirSides: Side[] = ([1, 2] as const).map((n) => {
      const handle = stripSponsor(String(e[`p${n}_name`] ?? ''));
      const key = isPlaceholderHandle(handle) ? '' : resolveKey(handle);
      const f = exactAlias(matcher, fighterCell(e, n), 'fighter');
      const supportRaw = supportCell(e, n);
      const s = exactAlias(matcher, supportRaw, 'support');
      return {
        players: key ? [key] : [],
        handle,
        fighters: f.id ? [f.id] : [],
        support: s.id ?? null,
        supportRaw,
      };
    });
    const ourSides: Side[] = mine.sides.map((s) => {
      const handle = stripSponsor(s.handle);
      const key = resolveKey(handle);
      return {
        players: key ? [key] : [],
        handle,
        fighters: s.characters,
        support: s.support ?? null,
        supportRaw: '',
      };
    });

    const score = (a: Side[], b: Side[]) =>
      a.reduce((n, s, i) => n + (s.players.some((p) => b[i]!.players.includes(p)) ? 1 : 0), 0);
    const flipped = score(ourSides, [theirSides[1]!, theirSides[0]!]) > score(ourSides, theirSides);
    if (flipped) r.players.flipped++;
    pairs.push({
      videoId,
      title: mine.title,
      ours: ourSides,
      theirs: flipped ? [theirSides[1]!, theirSides[0]!] : theirSides,
    });
  }

  // ── the blind spots, derived ────────────────────────────────────────────
  // THE CATALOGUE'S WHOLE VOCABULARY, read off the whole pull rather than off the
  // compared subset: a fighter it names once on a video we do not hold is still a
  // fighter it can name. Only ids it never once spoke are candidates; of those,
  // only the ones it consistently REPLACES with a single other id. Condition 1
  // alone would be unsafe on a thin pull — a two-page morning sees a fraction of
  // the roster — and condition 2 is what survives it.
  const spoken = new Set<string>();
  for (const e of entries) {
    for (const side of [1, 2] as const) {
      const f = exactAlias(matcher, fighterCell(e, side), 'fighter');
      if (f.id) spoken.add(f.id);
    }
  }
  const chances = new Map<string, number>();
  const instead = new Map<string, Map<string, number>>();
  for (const p of pairs) {
    for (let i = 0; i < 2; i++) {
      const said = p.theirs[i]!.fighters;
      for (const c of p.ours[i]!.fighters) {
        if (spoken.has(c)) continue;
        chances.set(c, (chances.get(c) ?? 0) + 1);
        const tally = instead.get(c) ?? new Map<string, number>();
        for (const id of said) tally.set(id, (tally.get(id) ?? 0) + 1);
        instead.set(c, tally);
      }
    }
  }
  const blind = new Map<string, BlindSpot>();
  for (const [id, sides] of chances) {
    const top = [...(instead.get(id) ?? new Map<string, number>())].sort((a, b) => b[1] - a[1])[0];
    if (!top) continue;
    if (sides < BLIND_SPOT_MIN_SIDES || top[1] / sides < BLIND_SPOT_CONCENTRATION) continue;
    blind.set(id, { id, mergedInto: top[0], merged: top[1], sides });
  }
  // A cursor pull is ADDITIVE: absence of evidence in a hundred entries is not
  // evidence of absence. A FULL sweep has seen the whole catalogue, so what it
  // does not re-derive is genuinely gone and is allowed to lapse.
  if (witness.mode !== 'full') {
    for (const b of carriedBlindSpots) if (!blind.has(b.id)) blind.set(b.id, b);
  }
  r.blindSpots = [...blind.values()].sort((a, b) => b.sides - a.sides || a.id.localeCompare(b.id));

  // ── pass 2: score ───────────────────────────────────────────────────────
  for (const p of pairs) {
    // A PLACEHOLDER SIDE IS A WITNESS THAT DECLINED TO ANSWER. Held out of the
    // player score entirely; the characters are still compared, because
    // "somebody (Katara/Kanna)" is a perfectly good character claim. There are
    // none in this catalogue — and the predicate is parse's own, the one that
    // treats `♱` as a real player rather than as punctuation (parse.ts:534-551).
    const placeholder = p.theirs.some((s) => isPlaceholderHandle(s.handle));
    if (placeholder) {
      r.players.placeholder++;
    } else {
      const hits = p.ours.reduce(
        (n, s, i) => n + (s.players.some((x) => p.theirs[i]!.players.includes(x)) ? 1 : 0),
        0,
      );
      for (let i = 0; i < 2; i++) {
        const mineKey = p.ours[i]!.players[0] ?? '';
        const theirKeys = p.theirs[i]!.players;
        if (theirKeys.includes(mineKey)) continue;
        if (mineKey && theirKeys.some((x) => x !== mineKey && mineKey.includes(x))) {
          r.players.handleAffix.ours++;
        } else if (mineKey && theirKeys.some((x) => x !== mineKey && x.includes(mineKey))) {
          r.players.handleAffix.theirs++;
        } else {
          r.players.handleAffix.unrelated++;
        }
      }
      if (hits === 2) r.players.both++;
      else if (hits === 1) r.players.one++;
      else {
        r.players.neither++;
        r.disagreements.push({
          videoId: p.videoId,
          field: 'players',
          ours: p.ours.flatMap((s) => s.players),
          theirs: p.theirs.flatMap((s) => s.players),
          title: p.title,
        });
      }
    }

    for (let i = 0; i < 2; i++) {
      // ── fighters ────────────────────────────────────────────────────────
      r.characters.sides++;
      const mineChars = p.ours[i]!.fighters;
      // A SIDE OF OURS THE CATALOGUE HAS NO WORD FOR. Checked before anything it
      // said, because it does not matter what it said: it could not have agreed.
      if (mineChars.some((c) => blind.has(c))) {
        r.characters.blindSpot++;
      } else if (p.theirs[i]!.fighters.length === 0) {
        // EXACT ALIAS ONLY. A catalogue string the roster does not know is not a
        // disagreement — it is a witness we cannot read, and guessing at it is how
        // a second witness becomes a second parser.
        r.characters.unreadable++;
      } else if (mineChars.length > FIGHTER_CAP) {
        r.characters.overCap++;
      } else if (setEq(mineChars, p.theirs[i]!.fighters)) {
        r.characters.agree++;
      } else {
        r.characters.disagree++;
        r.disagreements.push({
          videoId: p.videoId,
          field: 'characters',
          side: i,
          ours: mineChars,
          theirs: p.theirs[i]!.fighters,
          title: p.title,
        });
      }

      // ── supports, the second namespace ──────────────────────────────────
      r.supports.sides++;
      const theirSupport = p.theirs[i]!.support;
      const theirFighter = p.theirs[i]!.fighters[0];
      if (theirSupport && theirFighter && supportIndex.ownerOf(theirSupport) !== theirFighter) {
        // The catalogue's OWN invariant, not ours: every support belongs to
        // exactly one fighter across all 462 sides of the 2026-09-16 sweep. A
        // violation is a row to look at rather than a pick to file, and it is
        // counted here because this is the only place both columns of one row are
        // resolved side by side.
        r.supports.ownerMismatch++;
      }
      if (!theirSupport) {
        if (p.theirs[i]!.supportRaw) r.supports.unreadable++;
      } else if (p.ours[i]!.support === null) {
        r.supports.weSilent++;
      } else if (p.ours[i]!.support === theirSupport) {
        r.supports.agree++;
      } else {
        r.supports.disagree++;
        r.disagreements.push({
          videoId: p.videoId,
          field: 'supports',
          side: i,
          ours: [p.ours[i]!.support!],
          theirs: [theirSupport],
          title: p.title,
        });
      }
    }
  }
  r.characters.cannotWitness =
    r.characters.blindSpot + r.characters.unreadable + r.characters.overCap;
  r.disagreements.sort(
    (a, b) =>
      a.videoId.localeCompare(b.videoId) ||
      a.field.localeCompare(b.field) ||
      (a.side ?? -1) - (b.side ?? -1),
  );
  return r;
}

const pct = (n: number, total: number) =>
  total === 0 ? '—' : `${((n / total) * 100).toFixed(2)}%`;

/**
 * The report.md block, rendered from the COMMITTED artifact rather than from a
 * run's result — see the header. Byte-identical between full sweeps, which is
 * what keeps a quiet morning quiet. Returns nothing until a full sweep has
 * measured once.
 */
export function formatCrossCheck(art: WitnessArtifact): string[] {
  const m = art.measured;
  if (!m) return [];
  const ind = m.independence;
  const c = m.characters;
  const s = m.supports;
  const witnessable = c.agree + c.disagree;
  const scored = m.players.both + m.players.one + m.players.neither;
  const a = m.players.handleAffix;
  const affixTotal = a.ours + a.theirs + a.unrelated;
  const nearDependent = ind.chapterTranscribed + ind.titleTranscribed;
  return [
    '## Replay Theater cross-check',
    '',
    `A second reading of **${m.compared}** of our own records — videos the catalogue indexes`,
    'exactly once that we also parse from a tracked channel. It changes nothing: a',
    'disagreement is recorded in data/theater-disagreements.json with both claims, never',
    'written into a record. The catalogue does not outrank a confident parse and never',
    'outranks a human override.',
    '',
    `_Measured on the last full sweep, at catalogue entry ${m.atEntryId}. ${m.unmatched} catalogue video(s) are_`,
    `_ones we do not hold from a tracked channel; ${m.segmented} are VODs the catalogue segments, which_`,
    '_the intake owns and which have no single claim to compare against._',
    '',
    '### How much of this witness is independent',
    '',
    'Checklist 12i says to measure the independence before banking the number, and on a',
    'catalogue that is mostly SEGMENTS the siblings’ one-number answer (does the',
    'submission date match the upload date?) asks the wrong question — a segment’s',
    'submitter was not reading the video title at all. Three ways, over the',
    `**${ind.rows}** row(s) this sweep joined:`,
    '',
    '| where the names could have come from | rows | share |',
    '| --- | ---: | ---: |',
    `| a chapter of the video already names both | ${ind.chapterTranscribed} | ${pct(ind.chapterTranscribed, ind.rows)} |`,
    `| the VOD title names both | ${ind.titleTranscribed} | ${pct(ind.titleTranscribed, ind.rows)} |`,
    `| one name appears, the other does not | ${ind.partial} | ${pct(ind.partial, ind.rows)} |`,
    `| **neither — read off the footage** | **${ind.independent}** | **${pct(ind.independent, ind.rows)}** |`,
    '',
    `**${nearDependent}** row(s) are NEAR-DEPENDENT: the text was already there to copy, so agreement`,
    'on them is a consistency check on two readings of one string rather than verification',
    `against footage. **${ind.independent}** are not. For comparison, the siblings’ date signal reads`,
    `${pct(ind.sameDay, ind.rows)} same-day here.`,
    ...(ind.unjoined > 0
      ? [
          '',
          `_${ind.unjoined} row(s) of the read window point at a VOD this pull did not join, so they are_`,
          '_excluded from the shares above rather than counted as independent._',
        ]
      : []),
    '',
    '### What the two readings agree on',
    '',
    '| field | population | agree | disagree | cannot witness |',
    '| --- | ---: | ---: | ---: | ---: |',
    `| players (both handles) | ${scored} | ${m.players.both} (${pct(m.players.both, scored)}) | ${m.players.neither} | ${m.players.placeholder} |`,
    `| fighters (per side) | ${c.sides} | ${c.agree} (${pct(c.agree, c.sides)}) | ${c.disagree} | ${c.cannotWitness} |`,
    `| supports (per side) | ${s.sides} | ${s.agree} (${pct(s.agree, s.sides)}) | ${s.disagree} | ${s.weSilent + s.unreadable} |`,
    '',
    `Exactly one handle matched on **${m.players.one}** record(s). Side order differed on **${m.players.flipped}**; the`,
    'comparison realigns on the handles before reading characters, so a swapped pair is not',
    'counted twice as a character disagreement. Handles are compared sponsor-stripped on both',
    'sides.',
    '',
    `**${s.weSilent}** support side(s) are ones the catalogue states and WE DO NOT — not a`,
    'disagreement, and not a gap to be filled from here: 27 of the 32 title channels never',
    'state a support at all, which is why the index intake exists. The catalogue’s own owner',
    `partition holds on ${s.ownerMismatch === 0 ? 'every compared row' : `all but ${s.ownerMismatch} compared row(s)`}.`,
    '',
    ...(c.cannotWitness > 0
      ? [
          `**${c.cannotWitness}** fighter side(s) the catalogue COULD NOT HAVE GOT RIGHT are held out of the`,
          `column above: agreement over the ${witnessable} it can express is **${pct(c.agree, witnessable)}**.`,
          '',
          ...(art.blindSpots.length
            ? [
                'Its vocabulary has no word for these, derived from the sweep rather than declared —',
                'no string anywhere in the pull resolves to the id, and where we say it the catalogue',
                'says one particular other thing almost every time:',
                '',
                ...art.blindSpots.map(
                  (b) =>
                    `- \`${b.id}\` → the catalogue writes \`${b.mergedInto}\` instead, on ${b.merged} of the ` +
                    `${b.sides} side(s) where we say it (${pct(b.merged, b.sides)}).`,
                ),
                '',
              ]
            : []),
          ...(c.unreadable > 0 || c.overCap > 0
            ? [
                `A further ${c.unreadable} carried a fighter string that resolves to no roster id, and ${c.overCap}`,
                'named more fighters on our side than the catalogue can hold in its ONE fighter column',
                '— a counter-pick inside a set, which `MatchSide.characters` expresses and the',
                'catalogue cannot.',
                '',
              ]
            : []),
        ]
      : []),
    ...(affixTotal > 0
      ? [
          `Of the ${affixTotal} side(s) whose handles did not match, **${a.ours}** are ours carrying extra text the`,
          `catalogue does not, **${a.theirs}** are theirs carrying a team tag THEATER_SPONSOR does not strip`,
          `yet (the catalogue writes space-separated tags — "HOC Faulty", "SOZ tofuboi" — which that`,
          `pattern deliberately does not touch), and **${a.unrelated}** are genuinely different names, the only`,
          'bucket worth reading one row at a time. Reported, never scored: substring matching on',
          'handles is the kind of guessing this module refuses.',
          '',
        ]
      : []),
    ...(art.disagreements.length
      ? [
          `**${art.disagreements.length} disagreement(s)** — both claims, ours first:`,
          '',
          ...art.disagreements
            .slice(0, 25)
            .map(
              (d) =>
                `- \`${d.videoId}\`${d.side !== undefined ? ` side ${d.side}` : ''} ${d.field}: ` +
                `**${d.ours.join(', ') || '(none)'}** vs catalogue **${d.theirs.join(', ') || '(none)'}** — ${d.title.slice(0, 70)}`,
            ),
          ...(art.disagreements.length > 25 ? [`- … ${art.disagreements.length - 25} more`] : []),
          '',
        ]
      : ['No disagreements on that sweep.', '']),
  ];
}

// ── the entry point: read the witness, write the artifact, READ IT BACK ─────

const readJson = async <T>(path: string, fallback: T): Promise<T> => {
  if (!existsSync(path)) return fallback;
  return JSON.parse(await readFile(path, 'utf8')) as T;
};

async function main(): Promise<void> {
  if (!existsSync(WITNESS)) {
    console.error(
      [
        `✖ No witness at raw/replayTheater.witness.json.`,
        `  It is written by the pull, beside the intake dump:`,
        `    npm run data:theater -- --full`,
        `  raw/ is gitignored, so a fresh checkout never has one.`,
      ].join('\n'),
    );
    process.exit(1);
  }
  const witness = await readJson<WitnessFile>(WITNESS, {});
  const committed = await readJson<MatchVideo[]>(join(DATA, 'videos.json'), []);
  const [characters, supports] = await Promise.all([loadCharacters(), loadSupports()]);
  const matcher = buildAliasMatcher(characters, supports);
  const supportIndex = buildSupportIndex(supports);

  const before = await readJson<WitnessArtifact>(ARTIFACT, { blindSpots: [], disagreements: [] });
  const result = crossCheck(
    witness,
    committed,
    matcher,
    supportIndex,
    playerId,
    stripTheaterSponsor,
    before.blindSpots,
  );

  const ind = result.independence;
  console.log(
    `\n▶ Replay Theater cross-check — witness mode ${witness.mode ?? '(none)'}, ` +
      `${witness.entries?.length ?? 0} entr(ies) over ${witness.pagesRead ?? 0} page(s), ` +
      `${Object.keys(witness.videos ?? {}).length} VOD(s) joined`,
  );
  console.log(
    `  independence: ${ind.chapterTranscribed} chapter-transcribed + ${ind.titleTranscribed} ` +
      `title-transcribed = ${ind.chapterTranscribed + ind.titleTranscribed} near-dependent · ` +
      `${ind.partial} partial · ${ind.independent} INDEPENDENT of ${ind.rows} classified` +
      (ind.unjoined ? ` (${ind.unjoined} unjoined)` : ''),
  );
  console.log(
    `  (Stage 0 read 66 / 57 / 91 over the 231-row sweep of 2026-09-16 — this is a ` +
      `re-measurement, not a restatement)`,
  );
  console.log(
    `  compared ${result.compared} record(s); ${result.unmatched} catalogue video(s) we do not ` +
      `hold, ${result.segmented} the catalogue segments`,
  );
  console.log(
    `  players ${result.players.both} both / ${result.players.one} one / ${result.players.neither} ` +
      `neither · fighters ${result.characters.agree} agree / ${result.characters.disagree} ` +
      `disagree / ${result.characters.cannotWitness} cannot witness · supports ` +
      `${result.supports.agree} agree / ${result.supports.disagree} disagree / ` +
      `${result.supports.weSilent} we-silent`,
  );

  // A CURSOR MORNING MEASURES A WINDOW, NOT A CORPUS. It prints the reading above
  // and leaves the committed artifact alone, or report.md changes every day
  // whether or not a record did.
  if (witness.mode !== 'full') {
    console.log(
      `\n  cursor mode: nothing written. data/theater-disagreements.json still holds the last ` +
        `full sweep's reading` +
        (before.measured ? ` (entry ${before.measured.atEntryId})` : ' (none yet)') +
        `.\n  Measure and commit with: npm run data:theater -- --full && npx tsx scripts/crosscheck.ts`,
    );
  } else {
    const artifact: WitnessArtifact = {
      measured: {
        atEntryId: witness.maxEntryId ?? 0,
        compared: result.compared,
        unmatched: result.unmatched,
        segmented: result.segmented,
        players: result.players,
        characters: result.characters,
        supports: result.supports,
        independence: result.independence,
      },
      blindSpots: result.blindSpots,
      disagreements: result.disagreements,
    };
    await writeFile(ARTIFACT, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');

    // ── READ BACK WHAT WAS JUST WRITTEN, AND CHECK IT AGAINST THE READING ──
    // Every later run renders report.md from the FILE, not from a measurement in
    // memory. So a field that does not survive the write leaves the file quietly
    // thinner than the reading, and every report after it is wrong in a way no
    // run can see — because the run that wrote it rendered from memory and was
    // always right.
    //
    // THE COMPARISON IS AGAINST `result`, NOT AGAINST THE BYTES, AND THAT IS THE
    // WHOLE POINT. A byte compare of stringify(parse(s)) against s is very nearly
    // a tautology: JSON.stringify already turns a Map, a Set, an undefined and a
    // NaN into `{}`, `{}`, nothing and `null` on the way OUT, so the read-back
    // reproduces them exactly and the compare passes. Verified by injecting a Map
    // into this object and watching a byte compare report success. Comparing the
    // re-read numbers with the numbers crossCheck actually returned is not
    // circular: it is the reading on one side and the file on the other, and a
    // field that JSON dropped is `undefined` here and fails.
    const back = await readJson<WitnessArtifact>(ARTIFACT, { blindSpots: [], disagreements: [] });
    const m = back.measured;
    const mismatches = (
      [
        ['compared', result.compared, m?.compared],
        ['unmatched', result.unmatched, m?.unmatched],
        ['segmented', result.segmented, m?.segmented],
        ['players.both', result.players.both, m?.players?.both],
        ['players.neither', result.players.neither, m?.players?.neither],
        ['characters.agree', result.characters.agree, m?.characters?.agree],
        ['characters.disagree', result.characters.disagree, m?.characters?.disagree],
        ['characters.cannotWitness', result.characters.cannotWitness, m?.characters?.cannotWitness],
        ['supports.agree', result.supports.agree, m?.supports?.agree],
        ['supports.disagree', result.supports.disagree, m?.supports?.disagree],
        ['supports.weSilent', result.supports.weSilent, m?.supports?.weSilent],
        ['independence.rows', result.independence.rows, m?.independence?.rows],
        [
          'independence.chapterTranscribed',
          result.independence.chapterTranscribed,
          m?.independence?.chapterTranscribed,
        ],
        [
          'independence.titleTranscribed',
          result.independence.titleTranscribed,
          m?.independence?.titleTranscribed,
        ],
        ['independence.partial', result.independence.partial, m?.independence?.partial],
        ['independence.independent', result.independence.independent, m?.independence?.independent],
        ['blindSpots', result.blindSpots.length, back.blindSpots?.length],
        ['disagreements', result.disagreements.length, back.disagreements?.length],
      ] as Array<[string, number, number | undefined]>
    ).filter(([, measured, onDisk]) => measured !== onDisk);
    if (mismatches.length) {
      throw new Error(
        [
          `data/theater-disagreements.json does not carry the reading that produced it:`,
          ...mismatches.map(([k, a, b]) => `  ${k}: measured ${a}, the file says ${String(b)}`),
          `A field did not survive the write. Every later report renders from the FILE, so`,
          `this would have been silent.`,
        ].join('\n'),
      );
    }
    console.log(
      `\n✓ data/theater-disagreements.json — measured at catalogue entry ` +
        `${witness.maxEntryId ?? 0}, ${mismatches.length === 0 ? 'read back and checked field by field' : ''}`,
    );
  }

  // Rendered from the committed file in both modes — which is the point.
  const committedArtifact = await readJson<WitnessArtifact>(ARTIFACT, {
    blindSpots: [],
    disagreements: [],
  });
  const block = formatCrossCheck(committedArtifact);
  if (block.length === 0) {
    console.log(
      `\n  (no full sweep has measured yet, so there is no report block to render — run ` +
        `npm run data:theater -- --full first)`,
    );
    return;
  }
  console.log(`\n${'─'.repeat(72)}`);
  console.log(block.join('\n'));
}

// isMain: the functions above are exported so a gate can exercise the comparison
// without a pull, and importing this module must not read or write anything.
const entry = process.argv[1];
const isMain = !!entry && import.meta.url.endsWith(entry.split('/').pop() ?? '');
if (isMain) main();
